### ISSUE TITLE
Poll January 2020: Choose the business area for our next community API!

### ISSUE THREAD

**Issue by openbankingproject** [openbankingproject-ch/obp-apis#13]
Dear community

Now it's up to you to set the direction for our **next Community API**. Together we will then proceed with the selection and operationalisation for Switzerland.
 
Please let us know your opinion **until Friday 31.01.2020** by clicking on a bar (no registration needed).  You are very welcome to comment underneath the poll.

Based on the previous input of our community, we would like to present the following candidates for business areas: 

![grafik](https://user-images.githubusercontent.com/50946869/73627882-b073e480-464e-11ea-8def-afa0dee79626.png)

Thanks for your support and for being part of our community!
https://www.openbankingproject.ch 

Join us on [Linkedin](https://www.linkedin.com/showcase/20342172/admin/) or [Twitter](https://twitter.com/obp_ch).

**Comment by openbankingproject-ch** [comment]
This poll is finished. Thank you very much for your participation! 
We will keep you posted on [Twitter](https://twitter.com/obp_ch) and [Linkedin](https://www.linkedin.com/showcase/openbankingproject.ch/) and you'll hear from us soon. : )

**Comment by openbankingproject** [comment]
This poll is finished. Thank you very much for your participation!
We will keep you posted on [Twitter ](https://twitter.com/obp_ch) and [Linkedin ](https://www.linkedin.com/showcase/openbankingproject.ch/)and you'll hear from us soon. : )
