### ISSUE TITLE
sepa-credit-transfer sample includes creditorAgent

### ISSUE THREAD

**Issue by smantel-ch** [openbankingproject-ch/obp-apis#14]
```json
{
  "endToEndIdentification": "54947df80e9e4471a2f99af509fb5889",
  "debtorAccount": {
    "iban": "CH2781412000006944106"
  },
  "debtorAgent": {
    "bic": "RAIFCH22E12"
  },
  "debtorName": "Example Sepaone",
  "instructedAmount": {
    "currency": "EUR",
    "amount": "5000.00"
  },
  "creditorAccount": {
    "iban": "DE80690700240048159800"
  },
  "creditorAgent": {
    "bic": "DEUTDEDB690"
  },
  "creditorName": "Kunde 3",
  "creditorAddress": {
    "townName": "Muenchen",
    "country": "DE",
    "postCode": "80036",
    "streetName": "Rosenauweg"
  },
  "chargeBearer": "SLEV",
  "serviceLevel": "SEPA",
  "requestedExecutionDate": "2019-10-22"
}
```

When sending a POST request to create a new sepa-credit-transfer with the sample request body the backend replies with

```json
{
  "category": "ERROR",
  "code": "FORMAT_ERROR",
  "text": "The field 'creditorAgent' is not expected in the request"
}
```

**Comment by chatelao** [comment]
Thanks, the agent was removed from the specification due the Swiss SEPA description (case 5).

1. We will check, if the agent is forbidden by the spec. or optional and ignored.
2. If you have a clear opinion on this point, please feel free to share it.

![image](https://user-images.githubusercontent.com/2461532/73010317-816d9f80-3e12-11ea-87c4-436822f8af51.png)
![image](https://user-images.githubusercontent.com/2461532/73010632-08bb1300-3e13-11ea-8fa3-c8c417c43c70.png)

**Comment by chatelao** [comment]
btw: there is an JSON issue with one of the SEPA examples too.

**Comment by chatelao** [comment]
Fix in current version of the Sandbox.
