### ISSUE TITLE
Description of transactionCurrency

### ISSUE THREAD

**Issue by yves-bussard** [openbankingproject-ch/obp-apis#31]
In the description for the Model **paymentInitiation_json** we have a table which defines for each property, whether it is mandatory or not (depending on the payment type).

While the name of the property in the model is **`transactionCurrency`** the table include this property as **`currencyOfTransfer`**.  Please rename the name in the table from **`currencyOfTransfer`** to **`transactionCurrency`** (do not rename the property).

The **`currencyOfTransfer`** references Footnote 1) in some columns. There is also a footnote 7) whose text refers to this property but it is never used. I don't know which footnote would be correct for this property: 1? 7? 1 AND 7?

If 7) is not used, then please remove it. If it is used then rename the property in the footnote too.

**NOTE: There is a corresponding table in periodic payments and bulk payments. Please apply the above corrections to ALL 3 tables and footnotes.**

**Comment by blehers** [comment]
Source of inaccuracy can also be found in the [documents ](https://www.berlin-group.org/nextgenpsd2-downloads)of Berlin Group.

- NextGenPSD2 XS2A Framework 1.3.8_2020-12-14: "transactionCurrency"
![grafik](https://user-images.githubusercontent.com/51756488/116193710-0e975680-a730-11eb-8f01-dd14712ec072.png)

- Domestic PIS and AIS Definitions 19.04.2021: "currencyOfTransfer"
![grafik](https://user-images.githubusercontent.com/51756488/116193891-5b7b2d00-a730-11eb-9a8d-6a7a3a6292f1.png)

In the [SIX Swiss Payment Standards](https://www.six-group.com/dam/download/banking-services/interbank-clearing/en/standardization/iso/swiss-recommendations/implementation-guidelines-ct.pdf) Version 1.11 19.11.2021 "currencyOfTransfer" is used.
![grafik](https://user-images.githubusercontent.com/51756488/116194420-1c99a700-a731-11eb-8b33-8f3280c9f8ff.png)

**I therefore suggest to use "currencyOfTransfer" throughout and adapt the API accordingly.**

**Comment by yves-bussard** [comment]
I'm not really convinced. Throughouot the yaml file, Berlin Group uses the name `transactionCurrency` consistently, even in descriptions:
![image](https://user-images.githubusercontent.com/11332955/116196240-8915a580-a733-11eb-8165-a26880aed1f0.png)

It is probably not possible to predict whether they are going to change the code (yaml file) according to the documentation or the documentation according to the code. If we go ahead and change the code (property name) then we change the API. If we change the description, the API remains the same and we just fixed a typo. Besides we stay more in line with PSD2.

Therefore I suggest we use `transactionCurrency` until Berlin Group changes it in the code.

**Comment by wishopt** [comment]
Closed, as this change has been merged to the master branch.
