### ISSUE TITLE
Remove non applicable properties

### ISSUE THREAD

**Issue by yves-bussard** [openbankingproject-ch/obp-apis#32]
In the table which describes all properties for each payment type two properties are **n.a.** for **each** payment type:

- remittanceInformationUnstructuredArray
- requestedExecutionTime

Why do we even mention them if they are never used? I suggest, we remove them.

**NOTE: There is a corresponding table in periodic payments and bulk payments. Please apply the above corrections to ALL 3 tables and footnotes.**

**Comment by blehers** [comment]
This follows the logic of the Berlin Group, which lists all available elements in each case. **I suggest to leave it like this.**

![grafik](https://user-images.githubusercontent.com/51756488/116195954-291eff00-a733-11eb-99c3-b823a308637f.png)

**Comment by yves-bussard** [comment]
After creating the issues #35, #36, #37, etc. I'm still not happy about the outcome of this issue. If the property is mentioned in the description of the model, it is ok. As mentioned by @blehers Berlin Group does it as well. 

Where we differ here is that we add the properties in the model even if they are n.a. for all types. Berlin Group DOES NOT offer n.a. properties in their models (e.g. requestedExecutionTime).

This makes for a clean API. Why should we give the developer the possibility to pass/accept a property which is not used and not validated? 

Therefore I suggest we remove them from the model but keep them in the description.

**Comment by yves-bussard** [comment]
Actually I wanted to reopen this.

**Comment by blehers** [comment]
Make a comment out of it as Berlin Group does instead of removing in the model completly
