### ISSUE TITLE
Remove or complete equivalentAmount

### ISSUE THREAD

**Issue by yves-bussard** [openbankingproject-ch/obp-apis#33]
In the table which describes all properties for each payment type there is a property `equivalentAmount` which is missing in the model `paymentInitiation_json`.

Either we remove that property from the description or we add it to the model.

**NOTE: There is a corresponding table in periodic payments and bulk payments. Please apply the above corrections to ALL 3 tables and footnotes.**

**Comment by chatelao** [comment]
In der Spezifikation ist das Feld hier in Prosa beschrieben:
- https://github.com/openbankingproject-ch/obp-apis/blob/8a448b249f17b11ee4ccc8265c46df352b5d8d14/swiss-ng-api.yaml#L6072
- https://github.com/openbankingproject-ch/obp-apis/blame/master/swiss-ng-api/README.md#L24

Im Objekt fehlt das Feld:
- https://github.com/openbankingproject-ch/obp-apis/blob/8a448b249f17b11ee4ccc8265c46df352b5d8d14/swiss-ng-api.yaml#L5988

**Comment by blehers** [comment]
In the [SIX Swiss Payment Standards](https://www.six-group.com/dam/download/banking-services/interbank-clearing/en/standardization/iso/swiss-recommendations/implementation-guidelines-ct.pdf) Version 1.11 19.11.2021 "equivalentAmount" is used.
![grafik](https://user-images.githubusercontent.com/51756488/116195221-35ef2300-a732-11eb-9331-3e2d311227c4.png)

**I therefore suggest to add the property "equivalentAmount" to the model of the API accordingly.**
