### ISSUE TITLE
Missing description for property `intermediaryAgent` in single payment

### ISSUE THREAD

**Issue by yves-bussard** [openbankingproject-ch/obp-apis#44]
The property `intermediaryAgent` exists in the model `paymentInitiation_json` but is not documented in the descritpion of this model.

Is this a property which should be removed or should the description be completed?

**Comment by wishopt** [comment]
The table in the yaml-file seems out of sync with the [SNG README.md](https://github.com/openbankingproject-ch/obp-apis/tree/master/swiss-ng-api)

Will be added with the next update of the table.
